FROM node:20

WORKDIR /app/backend

# here we are only copiyng the specific file from local machine to current directory
COPY backend/package*.json ./
RUN npm install

# here we are copies all the files from backend folder to curretn folder not making a copy of entire folder itself
COPY backend/. .
# here wer are creating copy of supabase folder itself
COPY shared ./shared
EXPOSE 4000

CMD [ "node","index.js" ]