FROM node:20

WORKDIR /app/executer

RUN apt-get update && apt-get install -y docker.io
COPY Executer/package*.json ./
RUN npm install

COPY Executer/. .
COPY Supabase ./Supabase
EXPOSE 5000

CMD [ "node", "executer.js" ]